---
- name: Add user
  hosts: all
  gather_facts: yes
  become: yes

  vars_files:
  - list-add-key-user.yml
  tasks:
  
   - name: Setup | authorized key upload
     authorized_key: user={{ item.username }} key="{{ lookup('file', 'pub_keys/{{ item.username }}.pub') }}" manage_dir=yes state=present
     with_items: '{{users}}'
